// frontend/src/app/features/auth/components/google-button/google-button.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { environment } from '../../../../../environments/environment'; // adjust path if needed
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-google-button',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './google-button.component.html',
  styleUrls: ['./google-button.component.css'],
})
export class GoogleButtonComponent {
  loading = false;

  constructor(private auth: AuthService) {}

  loginWithGoogle(): void {
    try {
      this.loading = true;

      const scope = 'openid email profile';
      const params = new URLSearchParams({
        client_id: environment.googleClientId,
        redirect_uri: `${environment.frontendUrl}/auth/google`,
        response_type: 'id_token',
        scope,
        nonce: crypto.randomUUID(),
        prompt: 'select_account',
      });

      const googleAuthUrl = `https://accounts.google.com/o/oauth2/v2/auth?${params.toString()}`;
      window.location.href = googleAuthUrl;
    } catch (error) {
      console.error('Failed to start Google OAuth flow:', error);
    } finally {
      this.loading = false;
    }
  }
}

<button
  type="button"
  class="google-btn w-100 d-flex align-items-center justify-content-center gap-2 rounded-3 fw-medium"
  (click)="loginWithGoogle()"
>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="20"
    height="20"
    viewBox="0 0 18 18"
  >
    <path
      fill="#4285F4"
      d="M17.64 9.2045c0-.638-.0573-1.2527-.1636-1.8409H9v3.4818h4.8436a4.1427 4.1427 0 0 1-1.7973 2.7173v2.26h2.9073c1.7018-1.5664 2.6864-3.8745 2.6864-6.6182z"
    />
    <path
      fill="#34A853"
      d="M9 18c2.43 0 4.4673-.8064 5.9564-2.1764l-2.9073-2.26c-.8064.54-1.8382.8573-3.049.8573-2.3445 0-4.3282-1.5827-5.0355-3.71H.9573v2.3264A9 9 0 0 0 9 18z"
    />
    <path
      fill="#FBBC05"
      d="M3.9645 10.7109a5.393 5.393 0 0 1 0-3.4218V4.9627H.9573a9 9 0 0 0 0 8.0746l3.0072-2.3264z"
    />
    <path
      fill="#EA4335"
      d="M9 3.5627c1.3209 0 2.5073.4545 3.4382 1.3454l2.5727-2.5727C13.4673.8918 11.43 0 9 0a9 9 0 0 0-8.0427 4.9627l3.0072 2.3264C4.6718 5.1454 6.6555 3.5627 9 3.5627z"
    />
  </svg>

  <span>Sign in with Google</span>
</button>

// frontend/src/components/auth/GoogleButton.vue
<script setup>
import config from "../../config/envManager";

function handleGoogle() {
  const scope = "openid email profile";
  const params = new URLSearchParams({
    client_id: config.google_client,
    redirect_uri: `${config.frontend_url}/auth/google`,
    response_type: "id_token",
    scope,
    nonce: crypto.randomUUID(),
    prompt: "select_account",
  });
  window.location.href = `https://accounts.google.com/o/oauth2/v2/auth?${params.toString()}`;
}
</script>

<template>
  <button
    @click="handleGoogle"
    type="button"
    class="flex items-center justify-center w-1/2 py-3 rounded-xl font-medium transition-all duration-300 transform active:scale-95 bg-gray-500/40 backdrop-blur-md border border-gray-400 text-white shadow-md hover:bg-gray-400/50 hover:shadow-lg"
  >
    <svg
      class="h-5 w-5 mr-2"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 48 48"
      aria-hidden="true"
    >
      <path
        fill="#EA4335"
        d="M24 9.5c3.54 0 6.72 1.22 9.21 3.6l6.85-6.85C35.64 2.47 30.15 0 24 0 14.62 0 6.57 5.36 2.69 13.11l7.98 6.2C12.57 13.18 17.92 9.5 24 9.5z"
      />
      <path
        fill="#4285F4"
        d="M46.08 24.56c0-1.57-.14-3.07-.39-4.56H24v9.09h12.45c-.54 2.79-2.18 5.15-4.63 6.74l7.39 5.73c4.31-3.98 6.87-9.86 6.87-17z"
      />
      <path
        fill="#FBBC05"
        d="M10.67 28.31a14.48 14.48 0 0 1-.76-4.31c0-1.5.28-2.94.76-4.31l-7.98-6.2A23.88 23.88 0 0 0 0 24c0 3.82.91 7.42 2.69 10.51l7.98-6.2z"
      />
      <path
        fill="#34A853"
        d="M24 48c6.48 0 11.92-2.14 15.89-5.82l-7.39-5.73c-2.05 1.38-4.68 2.2-8.5 2.2-6.08 0-11.43-3.68-13.33-9.01l-7.98 6.2C6.57 42.64 14.62 48 24 48z"
      />
    </svg>
    Google
  </button>
</template>
